### ISSUE TITLE
Add token_filter argument to display_pca

### ISSUE THREAD

**Issue by jonthegeek** [jonathanbratt/RBERTviz#11]
As an RBERTviz user, I'd like to easily focus on tokens that match a particular regex, so that I can easily visualize a family of tokens.

The idea here would be, for example, to say `token_filter = "^train"` to filter the plot. Technically this could be done beforehand with the `keep_tokens` function, but I think it's easier if it's a parameter.

**Comment by jonathanbratt** [comment]
I was thinking about this the other day. Moving this into display_pca makes sense. In any case, I think `keep_tokens` should be deprecated. Originally, that function did more stuff, but now, there's really nothing it does that can't be done just as easily with a `dplyr::filter`.

**Comment by jonthegeek** [comment]
Per discussion, it's easy enough to just use filter, let's do/recommend that.
